# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment mappings — https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties — https://projects.neoforged.net/neoforged/neoforge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.228
neo_version_range=[21.1.228,)
loader_version_range=[1,)

## Mod Properties

mod_id=cointcore
mod_name=CointCore
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.mawlee.cointcore
mod_authors=mawlee
mod_description=Server-side coremod for COINT 1.2*. Install only on the dedicated server.
ftb_essentials_version=2101.1.9
ftb_library_version=2101.1.4
ftb_chunks_version=2101.1.15
ftb_teams_version=2101.1.8
curios_version=9.5.1+1.21.1
accessories_version=1.1.0-beta.51+1.21.1
