modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
displayTest="MATCH_VERSION"

[[mixins]]
config="${mod_id}.mixins.json"

[[mixins]]
config="${mod_id}.compat.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="SERVER"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="SERVER"

[[dependencies.${mod_id}]]
modId="luckperms"
type="optional"
versionRange="[5.4,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="ftbranks"
type="optional"
versionRange="[2101.1.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="ftbessentials"
type="optional"
versionRange="[2101.1.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="curios"
type="optional"
versionRange="[9.0.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="accessories"
type="optional"
versionRange="[1.0.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="ftbteams"
type="optional"
versionRange="[2101.1.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="ftbchunks"
type="optional"
versionRange="[2101.1.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="apothic_spawners"
type="optional"
versionRange="[1.0.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="spark"
type="optional"
versionRange="[1.0.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="tab"
type="optional"
versionRange="[5.5.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="placeholder-api"
type="optional"
versionRange="[2.0.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="ae2"
type="optional"
versionRange="[19.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="discord_chat_mod"
type="optional"
versionRange="[2.7.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="mob_grinding_utils"
type="optional"
versionRange="[1.1.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="rftoolsbuilder"
type="optional"
versionRange="[1.21-7.0.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="fluxnetworks"
type="optional"
versionRange="[8.0.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="oritech"
type="optional"
versionRange="[1.2.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="mahoutsukai"
type="optional"
versionRange="[1.21.1-v1.36.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="iceandfire"
type="optional"
versionRange="[2.0-beta.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="justdirethings"
type="optional"
versionRange="[1.5.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="enderio"
type="optional"
versionRange="[8.0.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="relics"
type="optional"
versionRange="[0.12.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="compactmachines"
type="optional"
versionRange="[1.0.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="hostilenetworks"
type="optional"
versionRange="[6.0.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="immersiveengineering"
type="optional"
versionRange="[12.0.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="railcraft"
type="optional"
versionRange="[1.2.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="stevescarts"
type="optional"
versionRange="[1.2.0,)"
ordering="AFTER"
side="SERVER"
